title:             Utopia Dispatch
email:             your-email@example.com
description:       The podcast reimagining the future and reshaping the world.
author:            Start Bootstrap
baseurl:           "/"
url:               "https://utopiadispatch.com"

# Social Profiles
twitter_username:  utopiadispatch
instagram_username:  utopiadispatch 
soundcloud_username: utopiadispatch
itunes_url_suffix: utopia-dispatch/id1241596769
spotify_url_suffix: 70HW5mqeJEM9MmblS83V3x?si=aNhL-iYOQM2U-2KlMxr7cw
email: hi@utopiadispatch.com
# github_username:   
# facebook_username: 

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
